Custom section here
<div class="mr-custom-section" data-bind="scope: 'myproduct'" id="mycustomsection">
	<p data-bind="text: customsection().customdata"></p>
</div>
<script type="text/x-magento-init">
	{
    	"#mycustomsection": {
        	"Magento_Ui/js/core/app": {
            	"components": {
                	"myproduct": {
                    	"component": "MageRocket_ExamDemo/js/section"
                	}
            	}
        	}
    	}
	}
</script>

<div id="custom-component" data-bind="scope:'customcomponent'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#custom-component": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "customcomponent": {
                        "component": "MageRocket_ExamDemo/js/custom-component"
                    }
                }
            }
        }
    }
    </script>
</div>